language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=2.0.4
  - DB=postresql

before_install:
  - cd virtualclinic

install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install coverage

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres
  - coverage run tests.py

script:
  - python manage.py test

after_success:
  - codecov
