language: python

python:
  - 3.5

services: postgresql

env:
  - DJANGO=2.0.4
  - DB=postresql

before_install:
  - cd virtualclinic

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py test
